config/routes.rb
Rails.application.routes.draw do
  get '/:year/:month/:day/:slug', controller: 'frontend_pieces', action: 'show', as: 'frontend_piece', constraints: {year: /\d{4}/, month: /\d{2}/, day: /\d{2}/}
  get '/authors/:id(/:page)', controller: 'frontend_authors', action: 'show', as: 'frontend_author'
  get '/tags/:id(/:page)', controller: 'frontend_tags', action: 'show', as: 'frontend_tag'
  get '/sections/:id(/:page)', controller: 'frontend_sections', action: 'show', as: 'frontend_section'
  get '/search/:query(/:page)', controller: 'frontend_pieces', action: 'search', as: 'frontend_search'

  get '/:volume/:number/:archivetag', controller: 'legacy_redirect', action: 'show_piece', constraints: {volume: /V\d+/, number: /N\d+/, archivetag: /[^\/]*\.html/}
  get '/:volume/:number/:parent/:archivetag', controller: 'legacy_redirect', action: 'show_piece', constraints: {volume: /V\d+/, number: /N\d+/, parent: /.*/, archivetag: /.*\.html/}

  namespace :api do
    get 'issue_lookup/:volume/:issue', action: 'issue_lookup'
    get 'article_as_xml/:id', action: 'article_as_xml'
    get 'newest_issue'
    get 'article_parts'
    get 'style_mapping'
  end

  scope '/admin' do
    get '/', to: 'static_pages#admin_homepage', as: :admin_root

    resources :article_lists, only: [:new, :create, :edit, :update, :index, :destroy, :show] do
      member do
        post 'append_item'
        post 'remove_item'
      end
    end

    resources :homepages, only: [:index, :show, :update] do
      member do
        post 'mark_publish_ready'
        post 'duplicate'
        post 'publish'
      end

      collection do
        get 'new_submodule_form'
        get 'new_row_form'
        post 'new_specific_submodule_form'
        post 'create_specific_submodule'
        post 'create_new_row'
      end
    end

    resources :issues, only: [:index, :show, :create] do
      member do
        get 'upload_pdf_form'
        post 'upload_pdf'
        delete 'remove_pdf'
      end
    end

    resources :authors

    resources :sections

    resources :series

    resources :pieces

    resources :images do
      resources :pictures, only: [:create, :destroy] do
        member do
          get 'direct'
        end
      end

      member do
        post 'unassign_piece'
        post 'assign_piece'
        post 'publish'
      end
    end

    resources :articles, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :article_versions, only: [:index, :show] do
        member do
          get 'revert'
          post 'publish'
          patch 'update_web_status'
          post 'mark_print_ready'
        end
      end

      member do
        get 'assets_list'
        patch 'update_rank'
      end
    end

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :users, only: [:index, :show, :edit, :update]

    get '/publish', controller: 'publishing', action: 'dashboard', as: 'publishing_dashboard'
    post '/publish', controller: 'publishing', action: 'publish'
  end

  root 'frontend_homepage#show'

  get '/:name', controller: 'frontend_static_pages', action: 'show', as: 'frontend_static_page', constraints: {name: /[^.]*/}

end

app/models/homepage.rb
class Homepage < AbstractModel
  serialize :layout

  before_save :assign_uuids

  SUBMODULE_TYPES = {
    'Article' => 'article',
    'Image' => 'img',
    'Image without caption' => 'img_nocaption',
    'Links' => 'links'
  }

  ROW_TYPES = {
    "1-1-1-1" => '1,1,1,1',
    "2-1-1" => '2,1,1',
    "1-2-1" => '1,2,1',
    "1-1-2" => '1,1,2',
    "3-1" => '3,1',
    "1-3" => '1,3',
    "2-2" => '2,2',
    "4" => '4'
  }

  enum status: [:draft, :publish_ready, :published]

  def self.generate_uuid
    SecureRandom.uuid
  end

  def self.latest_published
    self.published.order('created_at DESC').first
  end

  def fold_pieces
    output = []
    self.layout.each do |r|
      r[:modules].each do |m|
        m[:submodules].each do |s|
          if s[:type] == 'article'
            output << s[:piece]
          elsif s[:type] == 'links'
            output += s[:links]
          end
        end
      end
    end
    output.uniq
  end

  private
    def assign_uuids
      self.layout = self.layout.map(&:with_indifferent_access)

      self.layout.each do |row|
        row[:uuid] ||= generate_uuid

        row[:modules].each do |mod|
          mod[:uuid] ||= generate_uuid

          mod[:submodules].each do |submod|
            submod[:uuid] ||= generate_uuid
          end
        end
      end
    end

    def generate_uuid
      SecureRandom.uuid
    end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :set_homepage, except: [:index, :new_submodule_form, :new_row_form, :new_specific_submodule_form, :create_specific_submodule, :create_new_row]

  def index
    @homepages = Homepage.order('created_at DESC').limit(100)
  end

  def show
    @homepage = Homepage.find(params[:id])

    if @homepage.published? || @homepage.publish_ready?
      @homepage_warning = "Layout locked since it has already been marked ready for publication."
      @homepage_locked = true
    else
      @homepage_editing = true
    end

    gon.layout = @homepage.layout

    render 'frontend_homepage/show_homepage', layout: 'frontend'
  end

  def update
    @homepage = Homepage.find(params[:id])
    @homepage.update(layout: JSON.parse(params[:layout]))

    redirect_to homepage_path(@homepage), flash: {success: 'Successfully updated homepage. '}
  end

  def mark_publish_ready
    require 'varnish/purger'

    @homepage = Homepage.find(params[:id])
    @homepage.publish_ready!

    redirect_to homepage_path(@homepage), flash: {success: 'Successfully marked layout as publish ready. '}
  end

  def duplicate
    @homepage = Homepage.find(params[:id])

    nh = Homepage.create(layout: @homepage.layout)

    redirect_to homepage_path(nh), flash: {success: 'Successfully duplicated the layout. '}
  end

  def new_submodule_form
    @uuid = params[:module_uuid]

    respond_to do |f|
      f.js
    end
  end

  def new_row_form
    respond_to do |f|
      f.js
    end
  end

  def new_specific_submodule_form
    @uuid = params[:uuid]
    @mod_uuid = params[:mod_uuid]
    @type = params[:type]

    respond_to do |f|
      f.js
    end
  end

  def create_specific_submodule
    @type = params[:type]
    @uuid = params[:uuid]
    @mod_uuid = params[:mod_uuid]

    m = {uuid: @uuid, type: @type}

    case @type.to_sym
    when :article
      piece = Piece.find(params[:piece_id])
      m[:piece] = params[:piece_id]
      m[:headline] = piece.try(:article).try(:headline).try(:presence) || 'Empty headline'
      m[:lede] = piece.try(:article).try(:lede).try(:presence) || 'Empty lede'
    when :img, :img_nocaption
      picture = Picture.find(params[:picture_id])
      m[:picture] = params[:picture_id]
      m[:caption] = picture.try(:image).try(:caption).try(:presence) || 'Empty caption'
    when :links
      m[:links] = params[:links].select(&:present?)
    end

    @homepage_editing = true
    @content = render_to_string(partial: 'modules/submodule.html.erb', locals: {m: m})
    @json = m.to_json

    respond_to do |f|
      f.js
    end
  end

  def create_new_row
    @uuid = params[:uuid]
    @type = params[:type].split(',').map(&:to_i)

    row = {
      uuid: @uuid,
      modules: @type.map do |c|
        {
          uuid: Homepage.generate_uuid,
          cols: c,
          submodules: []
        }
      end
    }

    @homepage_editing = true
    @content = render_to_string(partial: 'frontend_homepage/row', locals: {row: row})
    @json = row.to_json

    respond_to do |f|
      f.js
    end
  end

  def publish
    @homepage = Homepage.find(params[:id])
    pieces = Piece.find(@homepage.fold_pieces)
    invalids = pieces.select { |p| !p.web_published? }

    if invalids.any?
      redirect_to publishing_dashboard_path, flash: {error: "Cannot publish layout since the following pieces have not been published yet: \n" + invalids.map(&:name).join("\n")}
    else
      @homepage.published!

      Varnish::Purger.purge(root_path, request.host)

      redirect_to publishing_dashboard_path, flash: {success: "You have successfully published the homepage layout. "}
    end
  end

  private
    def set_homepage
      @homepage = Homepage.find(params[:id])
    end
end

app/views/homepages/_master_editing_toolbar.html.erb
<div class="master-editing-toolbar">
  <% if @homepage_editing %>
    <%= form_tag homepage_path(homepage), method: :patch, id: 'save_layout_form' do %>
      <%= hidden_field_tag :layout %>
      <%= link_to 'Save Layout', '', id: 'save_layout' %>
    <% end %>

    <%= link_to 'Mark as Publish Ready', mark_publish_ready_homepage_path(homepage), method: :post, data: {confirm: 'Are you sure that you want to mark this layout as publish ready? '} %>
  <% end %>

  <%= link_to 'Duplicate this Layout', duplicate_homepage_path(homepage), method: :post %>

  <%= link_to 'Back to Layout List', homepages_path %>

  <% if flash && flash[:success] %>
    <span class="flash success"><%= flash[:success] %></span>
  <% end %>

  <% if @homepage_warning %>
    <span class="flash warning"><%= @homepage_warning %></span>
  <% end %>
</div>

app/views/homepages/_new_row_form.html.erb
<% uuid = Homepage.generate_uuid %>
<div class="new-row-form" data-uuid="<%= uuid %>">
  <%= form_tag create_new_row_homepages_path, remote: true do %>
    <%= hidden_field_tag :uuid, uuid %>

    <%= select_tag :type, options_for_select(Homepage::ROW_TYPES.map { |k, v| [k, v] }) %>

    <%= submit_tag 'Add New Row' %>
  <% end %>
</div>

app/views/homepages/_new_row_toolbar.html.erb
<div class="new-row-toolbar">
  <%= link_to 'Add New Row', new_row_form_homepages_path, remote: true %>
</div>

app/views/homepages/_new_submodule_form.html.erb
<% uuid = Homepage.generate_uuid %>
<div class="new-submodule-form" data-uuid="<%= uuid %>">
  <%= form_tag new_specific_submodule_form_homepages_path, remote: true do %>
    <%= hidden_field_tag :uuid, uuid %>
    <%= hidden_field_tag :mod_uuid, @uuid %>
    <%= select_tag :type, options_for_select(Homepage::SUBMODULE_TYPES.map { |k, v| [k, v] }) %>

    <%= submit_tag 'Add Submodule' %>
  <% end %>
</div>

app/views/homepages/_row_editing_toolbar.html.erb
<div class="row-editing-toolbar">
  <%= link_to "javascript: window.homepage.remove_row('#{row[:uuid]}'); ", data: {confirm: 'Do you really want to remove this entire row? '} do %>
    <i class="fa fa-times"></i>
  <% end %>

  <%= link_to "javascript: window.homepage.move_row_upward('#{row[:uuid]}'); " do %>
    <i class="fa fa-arrow-up"></i>
  <% end %>

  <%= link_to "javascript: window.homepage.move_row_downward('#{row[:uuid]}'); " do %>
    <i class="fa fa-arrow-down"></i>
  <% end %>
</div>

app/views/homepages/create_new_row.js.erb
$('[data-uuid=<%= @uuid %>]').replaceWith('<%=j @content %>');
window.homepage.append_row(<%= raw(@json) %>);

app/views/homepages/create_specific_submodule.js.erb
$('[data-uuid=<%= @uuid %>]').replaceWith("<%=j @content %>");
window.homepage.append_submodule("<%=j @mod_uuid %>", <%= raw(@json) %>);

app/views/homepages/duplicate.html.erb
<div class="page-header">
  <h1>Homepages#duplicate</h1>
</div>
<p>Find me in app/views/homepages/duplicate.html.erb</p>

app/views/homepages/index.html.erb
<div class="titleline">
  <h1>Homepage Layouts</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th class="center">Published?</th>
      <th class="center">Publish Ready?</th>
      <th>Created At</th>
      <th>Last Modified At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @homepages.each do |h| %>
      <tr>
        <td><%= h.id %></td>
        <td class="center"><%= link_to 'Yes', external_root_url if h.published? %></td>
        <td class="center"><%= 'Yes' if h.publish_ready? %></td>
        <td><%= time_ago_in_words h.created_at.to_s %> ago</td>
        <td><%= time_ago_in_words h.updated_at.to_s %> ago</td>
        <td><%= link_to 'View & Edit', homepage_path(h) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/homepages/new_row_form.js.erb
$('.new-row-toolbar').before("<%=j render 'new_row_form' %>");

app/views/homepages/new_specific_submodule_form.js.erb
$('[data-uuid=<%= @uuid %>]').html("<%=j render 'modules/forms/' + @type, uuid: @uuid, mod_uuid: @mod_uuid %>");

app/views/homepages/new_submodule_form.js.erb
$('.module[data-uuid=<%= @uuid %>] div:last').before('<%=j render "new_submodule_form" %>');

app/views/homepages/show.html.erb
<div class="page-header">
  <h1>Homepages#show</h1>
</div>
<p>Find me in app/views/homepages/show.html.erb</p>