config/routes.rb
Rails.application.routes.draw do
  get '/:year/:month/:day/:slug', controller: 'frontend_pieces', action: 'show', as: 'frontend_piece', constraints: {year: /\d{4}/, month: /\d{2}/, day: /\d{2}/}
  get '/authors/:id(/:page)', controller: 'frontend_authors', action: 'show', as: 'frontend_author'
  get '/tags/:id(/:page)', controller: 'frontend_tags', action: 'show', as: 'frontend_tag'
  get '/sections/:id(/:page)', controller: 'frontend_sections', action: 'show', as: 'frontend_section'
  get '/search/:query(/:page)', controller: 'frontend_pieces', action: 'search', as: 'frontend_search'

  get '/:volume/:number/:archivetag', controller: 'legacy_redirect', action: 'show_piece', constraints: {volume: /V\d+/, number: /N\d+/, archivetag: /[^\/]*\.html/}
  get '/:volume/:number/:parent/:archivetag', controller: 'legacy_redirect', action: 'show_piece', constraints: {volume: /V\d+/, number: /N\d+/, parent: /.*/, archivetag: /.*\.html/}

  namespace :api do
    get 'issue_lookup/:volume/:issue', action: 'issue_lookup'
    get 'article_as_xml/:id', action: 'article_as_xml'
    get 'newest_issue'
    get 'article_parts'
    get 'style_mapping'
  end

  scope '/admin' do
    get '/', to: 'static_pages#admin_homepage', as: :admin_root

    resources :article_lists, only: [:new, :create, :edit, :update, :index, :destroy, :show] do
      member do
        post 'append_item'
        post 'remove_item'
      end
    end

    resources :homepages, only: [:index, :show, :update] do
      member do
        post 'mark_publish_ready'
        post 'duplicate'
        post 'publish'
      end

      collection do
        get 'new_submodule_form'
        get 'new_row_form'
        post 'new_specific_submodule_form'
        post 'create_specific_submodule'
        post 'create_new_row'
      end
    end

    resources :issues, only: [:index, :show, :create] do
      member do
        get 'upload_pdf_form'
        post 'upload_pdf'
        delete 'remove_pdf'
      end
    end

    resources :authors

    resources :sections

    resources :series

    resources :pieces

    resources :images do
      resources :pictures, only: [:create, :destroy] do
        member do
          get 'direct'
        end
      end

      member do
        post 'unassign_piece'
        post 'assign_piece'
        post 'publish'
      end
    end

    resources :articles, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :article_versions, only: [:index, :show] do
        member do
          get 'revert'
          post 'publish'
          patch 'update_web_status'
          post 'mark_print_ready'
        end
      end

      member do
        get 'assets_list'
        patch 'update_rank'
      end
    end

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :users, only: [:index, :show, :edit, :update]

    get '/publish', controller: 'publishing', action: 'dashboard', as: 'publishing_dashboard'
    post '/publish', controller: 'publishing', action: 'publish'
  end

  root 'frontend_homepage#show'

  get '/:name', controller: 'frontend_static_pages', action: 'show', as: 'frontend_static_page', constraints: {name: /[^.]*/}

end

app/models/issue.rb
class Issue < AbstractModel
  has_many :pieces
  has_many :legacy_pages

  has_attached_file :pdf

  validates :volume, presence: true, numericality: {only_integer: true, greater_than: 0}
  validates :number, presence: true, numericality: {only_integer: true, greater_than: 0}, uniqueness: {scope: :volume, message: 'should be unique within a volume. '}
  validates :published_at, presence: true
  validates_attachment :pdf, :content_type => { :content_type => %w(application/pdf) }


  default_scope { order('volume DESC, number DESC') }

  # Returns an array of articles associated with this issue.
  def articles
    self.pieces.select { |p| !p.article.nil? }.map(&:article)
  end

  # Returns a user-friendly string representation of the name of this issue.
  def name
    "Volume #{volume} Issue #{number}"
  end

  # Return the issues grouped by volumes
  def self.volumes
    self.all.group_by(&:volume)
  end

  def published_at=(date)
     begin
       parsed = Date.strptime(date,'%m/%d/%Y')
       super parsed
     rescue
       super date
     end
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:upload_pdf_form, :upload_pdf, :remove_pdf, :show]

  load_and_authorize_resource

  respond_to :html

  def index
    @filter_volume = params[:filter_volume]
    @issues = nil

    if @filter_volume.present?
      @issues = Issue.where(volume: @filter_volume)
    else
      @issues = Issue.all
    end

    @issues = @issues.page(params[:page]).per(100)

    @new_issue = Issue.new
    respond_with(@issues)
  end

  def show
    @articles = @issue.pieces.with_article.reorder('section_id ASC').map(&:article).map(&:as_display_json).group_by { |x| x[:section_name] }
    @images = (@issue.pieces.with_image.map(&:image).to_a + @issue.pieces.with_article.map(&:article).map(&:asset_images).flatten).uniq { |i| i.id }.map(&:as_display_json)
  end

  def create
    @issue = Issue.new(issue_params)

    if @issue.save
      redirect_to issues_path, flash: {success: 'Successfully created issue. '}
    else
      redirect_to issues_path, flash: {error: @issue.errors.full_messages.join("\n")}
    end
  end

  def upload_pdf
    @issue.pdf = params[:content]

    if @issue.valid?
      @issue.save

      redirect_to issues_path, flash: {success: "Successfully uploaded PDF for #{@issue.name}. "}
    else
      redirect_to issues_path, flash: {error: "Please make sure the file you upload is a valid PDF file. "}
    end
  end

  def upload_pdf_form
  end

  def remove_pdf
    @issue.pdf = nil
    @issue.save

    redirect_to issues_path, flash: {success: "Successfully removed PDF for #{@issue.name}. "}
  end

  private
    def set_issue
      @issue = Issue.find(params[:id])
    end

    def issue_params
      params.require(:issue).permit(:number, :volume, :published_at)
    end
end

app/views/issues/_upload_pdf_form.html.erb
<%= form_tag upload_pdf_issue_path(issue), multipart: true do %>
  <span class="btn btn-info btn-file upload_pdf">
    Upload <%= file_field_tag "content", type: :file, multiple: true, onchange: '$(this).parents("form").submit()' %>
  </span>
<% end %>

app/views/issues/index.html.erb
<div class="titleline">
  <h1>
    <% if @filter_volume %>
      Issues in Volume <%= @filter_volume %>
    <% else %>
      Issues
    <% end %>
  </h1>

  <%= form_tag issues_path, method: :get, name: 'filter_issues' do %>
    <%= select_tag :filter_volume, options_for_select([['All Volumes', '']] + Issue.volumes.collect { |k, v| ["Volume #{k}", k] }, @filter_volume), class: 'form-control' %>
  <% end %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Volume</th>
      <th>Number</th>
      <th>Published On</th>
      <th>PDF</th>
      <th>Details</th>
    </tr>
  </thead>

  <tbody>
    <% if can? :create, Issue %>
      <tr>
        <%= form_for @new_issue do |f| %>
        <td><%= f.text_field :volume, class: 'form-control', placeholder: 'Volume number' %></td>
        <td><%= f.text_field :number, class: 'form-control', placeholder: 'Issue number' %></td>
        <td><%= f.text_field :published_at, class: 'form-control', placeholder: 'Published date, MM/DD/YYYY', data: {provide: 'datepicker'} %></td>
        <td colspan="2"><%= f.submit 'Create Issue', id: 'create_issue', class: 'btn btn-primary' %></td>
        <% end %>
      </tr>
    <% end %>

    <% can_upload_pdf = (can? :upload_pdf, @issues.first) %>
    <% can_remove_pdf = (can? :remove_pdf, @issues.first) %>

    <%= content_tag_for(:tr, @issues) do |issue| %>
      <td><%= issue.volume %></td>
      <td><%= issue.number %></td>
      <td><%= issue.published_at.try(:to_s, :long) %></td>
      <td id="issue_<%= issue.id %>_upload_pdf">
        <% if issue.pdf.present? %>
          <%= link_to 'View PDF', issue.pdf.url %>
          <% if can_remove_pdf %>
            <%= link_to 'Remove PDF', remove_pdf_issue_path(issue), data: {confirm: 'Do you really want to remove the uploaded PDF? '}, method: :delete %>
          <% end %>
        <% else %>
          <% if can_upload_pdf %>
            <%= link_to 'Upload', upload_pdf_form_issue_path(issue), remote: true %>
          <% end %>
        <% end %>
      </td>
      <td><%= link_to 'Details', issue_path(issue) %></td>
    <% end %>
  </tbody>
</table>

<%= paginate @issues, theme: 'twitter-bootstrap-3' %>

app/views/issues/show.html.erb
<div class="titleline">
  <h1><%= @issue.name %></h1>

  <%= link_to issues_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list"></span>
    Back
  <% end %>
</div>

<% @articles.each do |sec, articles| %>
  <h2><%= sec %></h2>

  <table class="table articles_table">
    <thead>
      <tr>
        <th class="center rank-column">Rank</th>
        <th class="center web-status-column">Web Published?</th>
        <th class="center print-status-column">Print Ready?</th>
        <th class="article-column">Article</th>
        <th class="versions-column"></th>
      </tr>
    </thead>
    <tbody>
      <%= render 'articles/article_list', json_articles: articles.sort_by { |a| a[:rank] }, mark_print_status: true, display_rank: true, hide_section_name: true %>
    </tbody>
  </table>
<% end %>

<% if @images.any? %>
  <h2>Images</h2>

  <table class="table">
    <thead>
      <tr>
        <th class="center">Publish Ready? </th>
        <th>Image</th>
        <th colspan="2"></th>
        <th class="center image_thumbnail_header">Thumbnail</th>
      </tr>
    </thead>
    <tbody>
      <%= render 'images/image_list', images: @images %>
    </tbody>
  </table>
<% end %>

app/views/issues/upload_pdf_form.js.erb
$('#issue_<%= @issue.id %>_upload_pdf').html("<%=j render 'upload_pdf_form', issue: @issue %>")