config/routes.rb
Rails.application.routes.draw do
  get '/:year/:month/:day/:slug', controller: 'frontend_pieces', action: 'show', as: 'frontend_piece', constraints: {year: /\d{4}/, month: /\d{2}/, day: /\d{2}/}
  get '/authors/:id(/:page)', controller: 'frontend_authors', action: 'show', as: 'frontend_author'
  get '/tags/:id(/:page)', controller: 'frontend_tags', action: 'show', as: 'frontend_tag'
  get '/sections/:id(/:page)', controller: 'frontend_sections', action: 'show', as: 'frontend_section'
  get '/search/:query(/:page)', controller: 'frontend_pieces', action: 'search', as: 'frontend_search'

  get '/:volume/:number/:archivetag', controller: 'legacy_redirect', action: 'show_piece', constraints: {volume: /V\d+/, number: /N\d+/, archivetag: /[^\/]*\.html/}
  get '/:volume/:number/:parent/:archivetag', controller: 'legacy_redirect', action: 'show_piece', constraints: {volume: /V\d+/, number: /N\d+/, parent: /.*/, archivetag: /.*\.html/}

  namespace :api do
    get 'issue_lookup/:volume/:issue', action: 'issue_lookup'
    get 'article_as_xml/:id', action: 'article_as_xml'
    get 'newest_issue'
    get 'article_parts'
    get 'style_mapping'
  end

  scope '/admin' do
    get '/', to: 'static_pages#admin_homepage', as: :admin_root

    resources :article_lists, only: [:new, :create, :edit, :update, :index, :destroy, :show] do
      member do
        post 'append_item'
        post 'remove_item'
      end
    end

    resources :homepages, only: [:index, :show, :update] do
      member do
        post 'mark_publish_ready'
        post 'duplicate'
        post 'publish'
      end

      collection do
        get 'new_submodule_form'
        get 'new_row_form'
        post 'new_specific_submodule_form'
        post 'create_specific_submodule'
        post 'create_new_row'
      end
    end

    resources :issues, only: [:index, :show, :create] do
      member do
        get 'upload_pdf_form'
        post 'upload_pdf'
        delete 'remove_pdf'
      end
    end

    resources :authors

    resources :sections

    resources :series

    resources :pieces

    resources :images do
      resources :pictures, only: [:create, :destroy] do
        member do
          get 'direct'
        end
      end

      member do
        post 'unassign_piece'
        post 'assign_piece'
        post 'publish'
      end
    end

    resources :articles, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :article_versions, only: [:index, :show] do
        member do
          get 'revert'
          post 'publish'
          patch 'update_web_status'
          post 'mark_print_ready'
        end
      end

      member do
        get 'assets_list'
        patch 'update_rank'
      end
    end

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :users, only: [:index, :show, :edit, :update]

    get '/publish', controller: 'publishing', action: 'dashboard', as: 'publishing_dashboard'
    post '/publish', controller: 'publishing', action: 'publish'
  end

  root 'frontend_homepage#show'

  get '/:name', controller: 'frontend_static_pages', action: 'show', as: 'frontend_static_page', constraints: {name: /[^.]*/}

end

app/models/article.rb
class Article < AbstractModel
  has_and_belongs_to_many :users
  has_many :authors, through: :authorships
  has_many :authorships
  has_many :article_versions

  belongs_to :piece
  belongs_to :latest_published_version, foreign_key: :latest_published_version_id, class_name: 'ArticleVersion'

  validates :headline, presence: true, length: {minimum: 2}

  serialize :chunks
  serialize :author_ids

  before_save :parse_html
  before_save :update_authors_line
  before_save :update_piece_published_fields
  after_save :update_authorships
  after_save :update_piece_web_template

  scope :published, -> { where('latest_published_version_id IS NOT NULL') }

  RANKS = ([99] + (0..98).to_a)

  include ArticleXmlExportable

  scope :search_query, lambda { |q|
    return nil if q.blank?

    terms = q.downcase.split(/\s+/)

    terms = terms.map { |e|
      ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }

    num_or_conds = 4
    where(
      terms.map { |t|
        "(LOWER(articles.headline) LIKE ? OR LOWER(articles.subhead) LIKE ? OR LOWER(articles.authors_line) LIKE ? OR LOWER(articles.bytitle) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  # Make sure that there is at least one version
  def article_versions
    self.save_version! if super.empty?
    super
  end

  # The latest published version.
  # Returns an instance of ArticleVersion
  def display_version
    ActiveSupport::Deprecation.warn("Article#display_version is deprecated. Use Article#latest_published_version instead. ")
    self.latest_published_version
  end

  # The latest version that has been marked ready for web publication.
  # Returns an instance of ArticleVersion
  def web_ready_version
    self.article_versions.web_ready.first
  end

  # The latest version which is ready for print
  def print_version
    self.article_versions.print_ready.first
  end

  # The latest version.
  # Returns an instance of ArticleVersion
  def latest_version
    self.article_versions.first
  end

  # The earliest published version.
  # Returns an instance of ArticleVersion
  def original_published_version
    self.article_versions.web_published.last
  end

  # Gives the publication time of the first version to be published.
  # Returns an instance of datetime. If the article has never been published,
  # returns nil.
  def published_at
    self.original_published_version.try(:updated_at)
  end

  # Gives the time of the most recent update to the latest published verison.
  # Returns an instance of datetime.
  def modified_at
    self.latest_published_version.try(:updated_at)
  end

  def published?
    ActiveSupport::Deprecation.warn("Article#published? is deprecated. Use Article#web_published? instead. ")
    self.web_published?
  end

  def web_published?
    !self.latest_published_version.nil?
  end

  def ready_for_print?
    !self.print_version.nil?
  end

  def unpublished?
    !self.published?
  end

  def has_pending_draft?
    first = self.article_versions.first
    first.web_status == "web_draft" and first.print_status == "print_draft"
  end

  # Returns the draft version of the article as an instance of Article_Version
  # if it exists. Otherwise, returns nil.
  def pending_draft
    has_pending_draft? ? self.article_versions.first : nil
  end

  # Parses a comma-separated string of author_ids into a list of
  # author_ids as integers.
  def author_ids=(author_ids)
    @author_ids = author_ids.split(',').map(&:to_i)
  end

  # Creates a comma separated string of author_ids, where the author_ids belong
  # to the authors of this article.
  def author_ids
    (@author_ids ||= self.authorships.map(&:author_id)).join(',')
  end

  # Returns a list of images associated with this article if there are any.
  # Otherwise, returns an empty list.
  def asset_images
    if self.piece
      self.piece.images
    else
      []
    end
  end

  def asset_article_lists
    self.piece.article_lists rescue []
  end

  def authors_line
    read_attribute(:authors_line) || authors_line_from_author_ids
  end

  # metas to be displayed
  def meta(name)
    case name
    when :headline, :subhead, :bytitle, :intro, :modified_at, :published_at, :syndicated?
      self.send(name)
    when :piece
      Piece.find_by(id: self.piece_id)
    when :authors
      Authorship.where(article_id: self.id).map(&:author)
    when :authors_line
      assemble_authors_line(self.meta(:authors))
    when :frontend_display_path
      self.piece.meta(:frontend_display_path)
    end
  end

  # virtual accessor intro for lede or automatically generated lede. If no lede
  # was specified, the lede is taken to be the first paragraph. If there is no
  # first paragraph, the string 'A rather empty piece.' is used as the lede.
  def intro
    if self.lede.blank?
      p = self.chunks.first

      if p
        Nokogiri::HTML.fragment(p).text
      else
        'A rather empty piece.'
      end
    else
      self.lede
    end
  end

  # This will simulate the controller save_version behavior. However, the params
  # will be generated instead of hand-crafted. This should only be used while
  # importing data
  def save_version!
    version = ArticleVersion.create(
      article_id: self.id,
      contents: {
        article_params: {
          headline: self.headline,
          subhead: self.subhead,
          bytitle: self.bytitle,
          html: self.html,
          author_ids: self.authorships.map(&:author_id).join(','),
          lede: self.lede
        },
        piece_params: {
          section_id: self.piece.section_id,
          primary_tag: self.piece.primary_tag,
          tags_string: self.piece.tags_string,
          issue_id: self.piece.issue_id
        },
        article_attributes: self.attributes,
        piece_attributes: self.piece.attributes,
        tag_ids: self.piece.taggings.map(&:tag_id).join(','),
        author_ids: self.authors.map(&:id).join(',')
      }
    )

    version.web_published!
    version.print_ready!

    version.created_at = self.updated_at
    version.updated_at = self.updated_at
    version.save

    self.latest_published_version = version
    save

    version
  end


  # Returns a json representation of the cached version of the article.
  def as_display_json
    Rails.cache.fetch("#{cache_key}/display_json") do
      {
        id: self.id,
        slug: self.piece.slug,
        rank: self.rank,
        is_published: self.published?,
        is_ready_for_print: self.ready_for_print?,
        has_pending_draft: self.has_pending_draft?,
        section_name: self.piece.section.name,
        headline: self.headline,
        subhead: self.subhead,
        authors_line: self.authors_line,
        bytitle: self.bytitle,
        issue: {volume: self.piece.issue.volume, number: self.piece.issue.number},
        publish_date: self.published_at,
        published_version_path: self.display_version && self.piece.frontend_display_path,
        print_version_path: self.print_version,
        latest_version_path: Rails.application.routes.url_helpers.article_article_version_path(self, self.latest_version),
        versions_path: Rails.application.routes.url_helpers.article_article_versions_path(self)
      }
    end
  end

  private

    # Parses the html content of the article and populates the chunks.
    def parse_html
      require 'parser'
      @parser = Techplater::Parser.new(self.html)
      @parser.parse!

      self.chunks = @parser.chunks
    end

    def update_piece_web_template
      self.piece.update(web_template: @parser.template)
    end

    def update_authors_line
      self.authors_line = authors_line_from_author_ids
    end

    # Creates a user-friendly string representation of the authors of this
    # article.
    def authors_line_from_author_ids
      authors = self.author_ids.split(',').map(&:to_i).map { |i| Author.find(i) }

      assemble_authors_line(authors)
    end

    # Given an array of Author instances, creates a user-friendly string
    # representation of the authors of this article.
    def assemble_authors_line(authors)
      case authors.size
      when 0
        "Unknown Author"
      when 1
        authors.first.name
      when 2
        "#{authors.first.name} and #{authors.last.name}"
      else
        (authors[0...-1].map(&:name) + ["and #{authors.last.name}"]).join(', ')
      end
    end

    def update_authorships
      self.authorships.destroy_all

      if @author_ids
        @author_ids.each_with_index do |author, order|
          self.authorships.create(
            author_id: author,
            rank: order
          )
        end
      end
    end

    def update_piece_published_fields
      return if self.latest_published_version.nil?

      self.piece.published_author_ids = self.latest_published_version.author_ids
      self.piece.published_tag_ids = self.latest_published_version.tag_ids
      self.piece.published_headline = self.latest_published_version.headline
      self.piece.published_subhead = self.latest_published_version.subhead
      self.piece.published_content = self.latest_published_version.content
      self.piece.published_section_id = self.latest_published_version.section_id

      self.piece.save
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :assets_list, :update_rank]
  before_action :prepare_authors_json, only: [:new, :edit]

  load_and_authorize_resource

  respond_to :html

  def index
    # Rough query syntax:
    #
    # If query looks like "  v343 N9394    " or "V134/N61" or "v100n1"
    #   then the articles from that issue are returned.
    # Otherwise
    #   articles are searched for matching headline or other metadata.

    match = /^\s*V(\d+)[ \/]?N(\d+)\s*$/i.match(params[:q])
    unless match.nil?
      issue = Issue.find_by(volume: match[1].to_i, number: match[2].to_i)
      @articles = issue.articles rescue []
    else
      @articles = Article.search_query(params[:q]).order('created_at DESC').limit(100)
    end

    @json_articles = @articles.map(&:as_display_json)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @article = Article.new
    @piece = Piece.new
    respond_with(@article)
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @piece = Piece.new(piece_params)

    if @article.valid? && @piece.valid?
      @article.piece = @piece
      @article.save

      redirect_to article_article_version_path(@article, save_version)
    else
      @flash[:error] = (@article.errors.full_messages + @piece.errors.full_messages).join("\n")
      render 'new'
    end
  end

  def update
    @article.assign_attributes(article_params)
    @piece.assign_attributes(piece_params)

    if @article.valid? && @piece.valid?
      @piece.save
      @article.save

      redirect_to article_article_version_path(@article, save_version)
    else
      @flash[:error] = (@article.errors.full_messages + @piece.errors.full_messages).join("\n")
      render 'edit'
    end
  end

  # This separate method is needed because we do not want to create a new
  # article version for each rank change.
  def update_rank
    @article.update(article_params.select { |k, v| k == 'rank' })

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @article.article_versions.destroy_all
    @article.piece.destroy
    @article.destroy
    respond_with(@article)
  end

  def assets_list
  end

  private
    def set_article
      @article = Article.find(params[:id])
      @piece = @article.piece
    end

    def article_params
      params.require(:article).permit(:headline, :subhead, :bytitle, :html, :section_id, :author_ids, :lede, :rank)
    end

    def piece_params
      params.permit(:section_id, :primary_tag, :tags_string, :issue_id, :syndicated, :slug)
    end

    def prepare_authors_json
      gon.authors = Author.all.map { |a| {id: a.id, name: a.name} }
      gon.prefilled_authors = @article.authors.map { |a| {id: a.id, name: a.name} } rescue []
    end

    def save_version
      version = ArticleVersion.create(
        article_id: @article.id,
        contents: {
          article_params: article_params,
          piece_params: piece_params,
          article_attributes: @article.attributes,
          piece_attributes: @piece.attributes,
          tag_ids: @piece.taggings.map(&:tag_id).join(','),
          author_ids: @article.authors.map(&:id).join(',')
        },
        user_id: @current_user.id
      )

      version.web_draft!
      version.print_draft!

      version
    end
end

app/views/articles/_article_list.html.erb
<% for article in json_articles %>
  <tr title="<%= article[:slug] %>" class="<%= 'not_ready' if (local_assigns[:mark_print_status] && !article[:print_version_path]) %>">

    <% unless local_assigns[:hide_section_name] %>
      <td class="center"><%= article[:section_name] %></td>
    <% end %>

    <% if local_assigns[:display_rank] %>
      <td class="center">
        <% if can? :update_rank, Article %>
          <%= form_for Article.find(article[:id]), remote: true, url: update_rank_article_url(article[:id]) do |f| %>
            <%= f.select :rank, Article::RANKS, {}, class: 'form-control' %>
          <% end %>
          <p id="update_rank_result_<%= article[:id] %>" class="update-rank-result"></p>
        <% else %>
          <%= article[:rank] %>
        <% end %>
      </td>
    <% end %>

    <td class="center">
      <% if article[:published_version_path].present? %>
        <a href="<%= article[:published_version_path] %>">Yes</a>
      <% end %>
    </td>

    <td class="center">
      <% if article[:print_version_path].present? %>
        <p>Yes</a>
      <% end %>
    </td>

    <td>
      <p class="headline">
        <span class="slug">
          <a href="<%= article[:latest_version_path] %>"><%= article[:slug] %></a>
        </span>
        •
        <%= article[:headline] %></p>
      <p>
        <span class="extra-info">
          V<%= article[:issue][:volume] %>
          N<%= article[:issue][:number] %>
          <% if article[:is_published] %>
            •
            Published online <%= date_in_words article[:publish_date] %>
          <% end %>
          <% if article[:has_pending_draft] %>
            •
            Has pending draft
          <% end %>
          •
          By <%= article[:authors_line] %>
        </span>
      </p>
    </td>

    <td><a href="<%= article[:versions_path] %>">Versions</a></td>
  </tr>
<% end %>

app/views/articles/_assets_list.html.erb
<% for list in article.asset_article_lists %>
  <a class="article_list btn btn-default" data-placeholder-html="<%= list.to_placeholder_html %>">List: <%= list.name %></a>
<% end %>

<% for image in article.asset_images %>
  <% for picture in image.pictures %>
    <img class="asset-candidate" src="<%= direct_image_picture_path(image, picture) %>">
  <% end %>
<% end %>

<%= link_to 'Create Image', new_image_path(piece_id: article.piece_id), target: '_blank', class: 'btn btn-default new-asset-btn' %>
<%= link_to 'Refresh Assets List', assets_list_article_path(article), remote: true, class: 'btn btn-default new-asset-btn' %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>

  <%= render 'pieces/embedded_fields', piece: @piece %>

  <hr>

  <div class="form-group">
    <%= f.label :headline %>
    <%= f.text_field :headline, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :subhead %>
    <%= f.text_field :subhead, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :author_ids, 'Authors' %>
    <%= f.text_field :author_ids, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :bytitle %>
    <%= f.text_field :bytitle, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :lede %>
    <%= f.text_area :lede, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :html, 'Content' %>
    <% if local_assigns[:is_new] %>
      <%= f.text_area :html, class: 'form-control ckeditor' %>
    <% else %>
      <div class="row">
        <div class="col-md-9">
          <%= f.text_area :html, class: 'form-control ckeditor' %>
        </div>
        <div class="col-md-3" id="article_assets_list">
          <%= render 'articles/assets_list', article: @article %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <% if local_assigns[:is_new] %>
      <%= f.submit 'Create Article', class: 'btn btn-primary' %>
    <% else %>
      <%= f.submit 'Update Article', class: 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/articles/assets_list.js.erb
$('#article_assets_list').html("<%=j render 'assets_list', article: @article %>")

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<hr>

<%= render 'articles/form' %>

app/views/articles/index.html.erb
<div class="titleline">
  <h1>Articles</h1>

  <%= link_to new_article_path, class: 'btn btn-primary', data: { no_turbolink: true } do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Article
  <% end %>
</div>

<table class="table" id="articles_table">
  <thead>
    <tr>
      <th class="center">Section</th>
      <th class="center">Web Published?</th>
      <th class="center">Print Ready?</th>
      <th>Article</th>
      <th></th>
    </tr>
    <tr>
      <td colspan="6">
        <%= form_tag articles_path, method: :get, remote: true do %>
          <input id="keywords" name="q" type="text" placeholder="Filter by keyword or by issue (e.g., 'v134 n61')" class="form-control">
        <% end %>
      </td>
    </tr>
  </thead>
  <tbody>
    <%= render 'article_list', json_articles: @json_articles %>
  </tbody>
</table>

app/views/articles/index.js.erb
$('#articles_table tbody').html("<%=j render 'article_list', json_articles: @json_articles %>")

app/views/articles/new.html.erb
<h1>New article</h1>

<hr>

<%= render 'form', is_new: true %>

app/views/articles/update_rank.js.erb
$("#update_rank_result_<%= @article.id %>").text('Success');