config/routes.rb
Rails.application.routes.draw do
  get '/:year/:month/:day/:slug', controller: 'frontend_pieces', action: 'show', as: 'frontend_piece', constraints: {year: /\d{4}/, month: /\d{2}/, day: /\d{2}/}
  get '/authors/:id(/:page)', controller: 'frontend_authors', action: 'show', as: 'frontend_author'
  get '/tags/:id(/:page)', controller: 'frontend_tags', action: 'show', as: 'frontend_tag'
  get '/sections/:id(/:page)', controller: 'frontend_sections', action: 'show', as: 'frontend_section'
  get '/search/:query(/:page)', controller: 'frontend_pieces', action: 'search', as: 'frontend_search'

  get '/:volume/:number/:archivetag', controller: 'legacy_redirect', action: 'show_piece', constraints: {volume: /V\d+/, number: /N\d+/, archivetag: /[^\/]*\.html/}
  get '/:volume/:number/:parent/:archivetag', controller: 'legacy_redirect', action: 'show_piece', constraints: {volume: /V\d+/, number: /N\d+/, parent: /.*/, archivetag: /.*\.html/}

  namespace :api do
    get 'issue_lookup/:volume/:issue', action: 'issue_lookup'
    get 'article_as_xml/:id', action: 'article_as_xml'
    get 'newest_issue'
    get 'article_parts'
    get 'style_mapping'
  end

  scope '/admin' do
    get '/', to: 'static_pages#admin_homepage', as: :admin_root

    resources :article_lists, only: [:new, :create, :edit, :update, :index, :destroy, :show] do
      member do
        post 'append_item'
        post 'remove_item'
      end
    end

    resources :homepages, only: [:index, :show, :update] do
      member do
        post 'mark_publish_ready'
        post 'duplicate'
        post 'publish'
      end

      collection do
        get 'new_submodule_form'
        get 'new_row_form'
        post 'new_specific_submodule_form'
        post 'create_specific_submodule'
        post 'create_new_row'
      end
    end

    resources :issues, only: [:index, :show, :create] do
      member do
        get 'upload_pdf_form'
        post 'upload_pdf'
        delete 'remove_pdf'
      end
    end

    resources :authors

    resources :sections

    resources :series

    resources :pieces

    resources :images do
      resources :pictures, only: [:create, :destroy] do
        member do
          get 'direct'
        end
      end

      member do
        post 'unassign_piece'
        post 'assign_piece'
        post 'publish'
      end
    end

    resources :articles, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :article_versions, only: [:index, :show] do
        member do
          get 'revert'
          post 'publish'
          patch 'update_web_status'
          post 'mark_print_ready'
        end
      end

      member do
        get 'assets_list'
        patch 'update_rank'
      end
    end

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    resources :users, only: [:index, :show, :edit, :update]

    get '/publish', controller: 'publishing', action: 'dashboard', as: 'publishing_dashboard'
    post '/publish', controller: 'publishing', action: 'publish'
  end

  root 'frontend_homepage#show'

  get '/:name', controller: 'frontend_static_pages', action: 'show', as: 'frontend_static_page', constraints: {name: /[^.]*/}

end

app/models/image.rb
# Schema information
#
# table: images
#
# caption		text
# attribution		text
# created_at		datetime
# updated_at 		datetime

class Image < AbstractModel
  has_and_belongs_to_many :users
  has_and_belongs_to_many :pieces

  enum web_status: [:web_draft, :web_published, :web_ready]
  enum print_status: [:print_draft, :print_ready]

  WEB_STATUS_NAMES = {
    web_draft: "Web Draft",
    web_published: "Web Published",
    web_ready: "Ready for Web"
  }

  PRINT_STATUS_NAMES = {
    print_draft: "Print Draft",
    print_ready: "Ready for Print"
  }

  belongs_to :primary_piece, class_name: 'Piece'

  has_many :pictures

  scope :search_query, lambda { |q|
    return nil if q.blank?

    terms = q.downcase.split(/\s+/)

    terms = terms.map { |e|
      ('%' + e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }

    num_or_conds = 2
    where(
      terms.map { |t|
        "(LOWER(images.caption) LIKE ? OR LOWER(images.attribution) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  def primary_picture_url(format)
    if pictures.first
      self.pictures.first.content.url(format)
    else
      nil
    end
  end

  def as_display_json
    Rails.cache.fetch("#{cache_key}/display_json") do
      {
        id: self.id,
        primary_slug: self.primary_piece.try(:slug),
        assigned_pieces: self.pieces.map(&:article).map(&:as_display_json),
        caption: self.caption,
        attribution: self.attribution,
        section_name: self.primary_piece.try(:section).try(:name),
        issue: {volume: self.primary_piece.try(:issue).try(:volume), number: self.primary_piece.try(:issue).try(:number)},
        thumbnail_path: self.primary_picture_url(:thumbnail)
      }
    end
  end

  def web_statuses_for_select
    if self.web_published?
      [:web_published]
    else
      Image.web_statuses.keys.reject { |k| k.to_sym == :web_published }
    end
  end

  private
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy, :direct, :assign_piece, :unassign_piece, :publish]

  load_and_authorize_resource

  respond_to :html

  def index
    @images = Image.search_query(params[:q]).order('created_at DESC').limit(100)
    @images = @images.map(&:as_display_json)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @assignable_pieces = Piece.with_article.recent.where.not(:id => @image.pieces.map(&:id).uniq)

    respond_with(@image)
  end

  def new
    @image = Image.new
    @piece = Piece.new
    respond_with(@image)
  end

  def edit
  end

  def create
    @image = Image.new(image_params)
    @piece = Piece.new(piece_params)

    @pictures = params[:images].map { |i| Picture.new(content: i) }

    piece_id = params[:piece_id]

    unless @pictures.all?(&:valid?)
      @flash[:error] = "Please make sure that all files are valid images. "
      render 'new' and return
    end

    unless @image.valid?
      @flash[:error] = @image.errors.full_messages.join("\n")
      render 'new' and return
    end

    if piece_id.blank?
      if @piece.valid?
        @pictures.each { |p| @image.pictures << p }
        @piece.save
        @image.primary_piece = @piece
        @image.save

        redirect_to @image
      else
        @flash[:error] = @piece.errors.full_messages.join("\n")
        render 'new'
      end
    else
      @pictures.each { |p| @image.pictures << p }
      @image.pieces << Piece.find(piece_id)
      @image.save

      redirect_to @image
    end
  end

  def update
    @image.assign_attributes(image_params)

    if @image.primary_piece.present?
      @piece = @image.primary_piece
      @piece.assign_attributes(piece_params)
    end

    if @image.valid?
      if @image.primary_piece.present?
        if @piece.valid?
          @piece.save
          @image.save

          redirect_to image_path(@image), flash: {success: 'You have successfully edited the image. '}
        else
          @flash[:error] = @image.errors.full_messages.join("\n")

          render 'edit'
        end
      else
        @image.save
        redirect_to image_path(@image), flash: {success: 'You have successfully edited the image. '}
      end
    else
      @flash[:error] = @image.errors.full_messages.join("\n")

      render 'edit'
    end
  end

  def destroy
    @image.destroy
    respond_with(@image)
  end

  def assign_piece
    piece = Piece.find(params[:piece_id])

    @image.pieces << piece
    @image.save

    redirect_to image_path(@image), flash: {success: 'The image is now assigned to the piece. '}
  end

  def unassign_piece
    piece = @image.pieces.find(params[:piece_id])

    if piece
      @image.pieces.delete(piece)
      redirect_to image_path(@image), flash: {success: 'The image is no longer assigned to the piece. '}
    else
      redirect_to image_path(@image), flash: {error: 'The image is not assigned to the piece in the first place. '}
    end
  end

  def publish
    @image.web_published!

    redirect_to publishing_dashboard_path, flash: {success: 'You have successfully published that image. '}
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:caption, :attribution, :content, :creation_piece_id, :section_id, :web_status, :print_status)
    end

    def piece_params
      params.permit(:section_id, :primary_tag, :tags_string, :issue_id, :syndicated, :slug)
    end
end

app/views/images/_form.html.erb
<%= form_for @image, :html => { :multipart => true } do |f| %>
  <% if local_assigns[:is_create] %>
    <div class="form-group">
      <%= label_tag :piece_id, 'Assigned piece' %>
      <%= select_tag :piece_id, options_for_select([['[Create New Piece]', nil]]) + options_from_collection_for_select(Piece.recent, :id, :name, local_assigns[:prefilled_piece_id]), {class: 'form-control'} %>
    </div>

    <%= render 'pieces/embedded_fields', piece: @piece %>
  <% end %>

  <% if @image.primary_piece.present? %>
    <%= render 'pieces/embedded_fields', piece: @piece || @image.primary_piece %>
  <% end %>

  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_field :caption, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :attribution %><br>
    <%= f.text_field :attribution, class: 'form-control' %>
  </div>


  <!-- Styling borrowed from http://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3/ -->

  <% if local_assigns[:is_create] %>
    <div class="form-group">
      <p id="filepath">
      </p>
      <span class="btn btn-info btn-file">
        Choose pictures <%= file_field_tag "images[]", type: :file, multiple: true %>
      </span>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Create Image', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/images/_image_list.html.erb
<% images.each do |i| %>
  <tr>
    <td class="center">Unknown</td>
    <td>
      <p>
        <% if i[:primary_slug] %>
          <span class="slug">
            <%= link_to i[:primary_slug], image_path(i[:id]) %>
          </span>
          •
        <% end %>
        <%= i[:caption].presence || 'Uncaptioned image' %>
        •
        <span class="attribution"><%= (i[:attribution].presence || 'No attribution present').upcase %></span>
      </p>

      <p class="attribution">

      </p>

      <% if i[:assigned_pieces].empty? %>
        <p>Not assigned to any pieces. </p>
      <% else %>
        <p>Assigned to: </p>
        <% i[:assigned_pieces].each do |p| %>
          <p>
            <span class="slug"><%= link_to p[:slug], p[:latest_version_path] %></span>
            •
            <%= p[:headline] %>
          </p>
        <% end %>
      <% end %>
    </td>
    <td><%= link_to 'Show', image_path(i[:id]) %></td>
    <td><%= link_to 'Edit', edit_image_path(i[:id]) %></td>
    <td>
      <% if i[:thumbnail_path] %>
        <img src="<%= i[:thumbnail_path] %>" class="image_thumbnail" alt="">
      <% else %>
        Empty Image
      <% end %>
    </td>
  </tr>
<% end %>

app/views/images/edit.html.erb
<div class="titleline">
  <h1>Editing Image</h1>
  <%= link_to images_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
</div>

<%= render 'form' %>

app/views/images/index.html.erb
<div class="titleline">
  <h1>Images</h1>
  <%= link_to new_image_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Image
  <% end %>
</div>

<table class="table" id="images_table">
  <thead>
    <tr>
      <th class="center">Publish Ready? </th>
      <th>Image</th>
      <th colspan="2"></th>
      <th class="center image_thumbnail_header">Thumbnail</th>
    </tr>
    <tr>
      <td colspan="5">
        <%= form_tag images_path, method: :get, remote: true do %>
          <input id="keywords" name="q" type="text" placeholder="Filter by caption or attribution. " class="form-control">
        <% end %>
      </td>
    </tr>
  </thead>
  <tbody>
    <%= render 'images/image_list', images: @images %>
  </tbody>
</table>

app/views/images/index.js.erb
$('#images_table tbody').html("<%=j render 'image_list', images: @images %>")

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form', is_create: true, prefilled_piece_id: params[:piece_id] %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <% if @image.caption.present? %>
      <h1><%= @image.caption %></h1>
    <% else %>
      <h1>Uncaptioned Image</h1>
    <% end %>

    <% if @image.attribution.present? %>
      <p id="attribution"><%= @image.attribution %></p>
    <% else %>
      <p id="attribution">No attribution present. </p>
    <% end %>

    <p>
      <% if @image.primary_piece %>
        <% for tag in @image.primary_piece.tags %>
          <span class="label label-primary"><%= tag %></span>
        <% end %>
      <% end %>
    </p>

    <% if @image.primary_piece %>
      <div class="form-group">
        <%= form_for(@image) do |f| %>
          <%= f.select :web_status, @image.web_statuses_for_select.to_a.map { |k| [Image::WEB_STATUS_NAMES[k.to_sym], k] }, {}, {class: 'form-control', data: {auto_submit: true}, disabled: @image.web_published?} %>
        <% end %>
      </div>

      <div class="form-group">
        <%= form_for(@image) do |f| %>
          <%= f.select :print_status, Image.print_statuses.keys.to_a.map { |k| [Image::PRINT_STATUS_NAMES[k.to_sym], k] }, {}, {class: 'form-control', data: {auto_submit: true}} %>
        <% end %>
      </div>
    <% end %>

    <table class="table" id="assigned_pieces">
      <tbody>
        <tr>
          <th>Assigned to Piece</th>
          <th>Actions</th>
        </tr>

        <% if @image.primary_piece %>
          <tr>
            <td><%= @image.primary_piece.name %></td>
            <td>

            </td>
          </tr>
        <% end %>

        <% for piece in @image.pieces %>
          <tr>
            <td><%= piece.name %></td>
            <td>
              <%= form_tag unassign_piece_image_path(@image) do %>
                <%= hidden_field_tag :piece_id, piece.id %>
                <%= submit_tag 'Unassign Piece', data: {confirm: 'Are you sure that you want to remove the piece from the list of assigned pieces? '} %>
              <% end %>
            </td>
          </tr>
        <% end %>

        <% unless @assignable_pieces.empty? %>
          <tr>
            <%= form_tag assign_piece_image_path(@image) do %>
              <td>
                <%= select_tag :piece_id, options_for_select(@assignable_pieces.map do |p|
                    [truncate(p.name, length: 50, separator: ' '), p.id]
                  end) %>
              </td>
              <td>
                <%= submit_tag 'Assign Piece' %>
              </td>
            <% end %>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>

  <div class="col-md-6">
    <div id="pictures_toggle" class="btn-group" role="group">
      <% @image.pictures.each_with_index do |p, i| %>
        <button class="btn btn-default" data-picture-id="picture_<%= i %>">Picture #<%= i %></button>
      <% end %>
    </div>

    <div id="pictures">
      <% if @image.pictures.empty? %>
        <p>No file attached to this image. </p>

        <%= form_tag image_pictures_path(@image), multipart: true do %>
          <span class="btn btn-info btn-file">
            Upload <%= file_field_tag "pictures[]", type: :file, multiple: true, id: 'images_field' %>
          </span>
        <% end %>
      <% else %>
        <% @image.pictures.each_with_index do |p, i| %>
          <div id="picture_<%= i %>">
            <%= image_tag p.content.url %>
            <%= link_to 'Remove Picture', image_picture_path(@image, p), method: :delete, class: 'btn btn-danger', data: {confirm: 'Do you really want to remove this picture? '} %>

            <%= form_tag image_pictures_path(@image), multipart: true, class: 'upload_pictures_form' do %>
              <span class="btn btn-info btn-file">
                Upload <%= file_field_tag "pictures[]", type: :file, multiple: true, id: 'images_field' %>
              </span>
            <% end %>
          </div>

        <% end %>
      <% end %>
    </div>
  </div>

</div>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>